version: 1.0.{build}
skip_tags: true
image: Visual Studio 2017
assembly_info:
  patch: true
  file: '**\AssemblyInfo.*'
  assembly_version: '{version}'
  assembly_file_version: '{version}'
  assembly_informational_version: '{version}'
before_build:
- cmd: nuget restore uSplit.sln
build:
  publish_nuget: true
  include_nuget_references: true
  verbosity: minimal
after_build:
- ps: >-
    (Get-Content src\Endzone.uSplit\Package.xml) -replace "<version>(.+)</version>", "<version>${env:APPVEYOR_BUILD_VERSION}</version>" | Out-File -Encoding "UTF8" src\Endzone.uSplit\Package.xml

    tools\Umbraco.Tools.Package.exe pack.json

    copy-item package.zip uSplit-umbraco-lt-7.5.zip

    rename-item package.zip "uSplit-${env:APPVEYOR_BUILD_VERSION}.zip"
test:
  assemblies:
    only:
    - Endzone.uSplit.Tests.dll
artifacts:
- path: uSplit-*.zip
  name: package
deploy:
- provider: Environment
  name: uSplit | Azure Blob Storage | Release
  on:
    branch: u7.5
- provider: Environment
  name: NuGet | Endzone.io
  on:
    branch: u7.5
notifications:
- provider: Slack
  auth_token:
    secure: 92lRw6lczG/kCWV5GJXyRls0+GObPruIrAz3MzLMgPflJXllSgm75CeWXUN60Vny
  channel: '#umbraco-plugins-notif'
  on_build_success: true
  on_build_failure: true
  on_build_status_changed: false